packages:
  - 'packages/*'
  - 'sites/*'

define: &zag_version '^0.65.0'

catalog:
  '@zag-js/svelte': *zag_version
  '@zag-js/react': *zag_version
  '@zag-js/accordion': *zag_version
  '@zag-js/avatar': *zag_version
  '@zag-js/rating-group': *zag_version
  '@zag-js/tabs': *zag_version
  '@zag-js/tags-input': *zag_version
  '@zag-js/progress': *zag_version
  '@zag-js/radio-group': *zag_version
  '@zag-js/switch': *zag_version
  typescript: '^5.5.4'
