blank_issues_enabled: true
contact_links:
  - name: Having problems with the CLI installer?
    url: https://github.com/skeletonlabs/create-skeleton-app/issues/new/choose
    about: Please report issues for the create-skeleton-app installer in its project repository.
  - name: Get support on Discord
    url: https://discord.com/channels/1003691521280856084/1151213014721241128
    about: Get help from the maintainers on Discord.
  - name: Ask a question, give feedbacks, share your project
    url: https://github.com/skeletonlabs/skeleton/discussions
    about: Connect with other community members with GitHub discussions.
