name: Publish Skeleton
on:
  push:
    branches:
      - nextdev/*

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  build_core:
    name: Build Skeleton Core
    uses: "./.github/workflows/checkout-and-install.yml"
    with:
      package_dir: packages/skeleton

  build_rest:
    needs: build_core
    strategy:
      matrix:
        framework: [packages/skeleton-svelte, packages/skeleton-react, packages/skeleton-vue]
    uses: "./.github/workflows/checkout-and-install.yml"
    with:
      package_dir: ${{ matrix.framework}}
